export const ROUTES = {
  home: '/',
  login: '/login',
  register: '/register',
  events: '/events',
  eventDetailPattern: '/events/:eventId',
  eventDetail: (eventId: string) => `/events/${eventId}`,
  checkoutPattern: '/checkout/:holdId',
  checkout: (holdId: string) => `/checkout/${holdId}`,
  paymentResultPattern: '/checkout/:holdId/result',
  paymentResult: (holdId: string) => `/checkout/${holdId}/result`,
  tickets: '/tickets',
  ticketDetailPattern: '/tickets/:ticketId',
  ticketDetail: (ticketId: string) => `/tickets/${ticketId}`,
  admin: '/admin',
  adminEvents: '/admin/events',
  adminEventNew: '/admin/events/new',
  adminEventEditPattern: '/admin/events/:eventId/edit',
  adminEventEdit: (eventId: string) => `/admin/events/${eventId}/edit`,
  adminVenueNew: '/admin/venues/new',
  adminVenueEditPattern: '/admin/venues/:venueId/edit',
  adminVenueEdit: (venueId: string) => `/admin/venues/${venueId}/edit`,
  notFound: '/not-found',
} as const
