export const ROUTES = {
  home: '/',
  login: '/login',
  register: '/register',
  events: '/events',
  admin: '/admin',
  adminEvents: '/admin/events',
  adminEventNew: '/admin/events/new',
  adminEventEditPattern: '/admin/events/:eventId/edit',
  adminEventEdit: (eventId: string) => `/admin/events/${eventId}/edit`,
  adminVenueNew: '/admin/venues/new',
  adminVenueEditPattern: '/admin/venues/:venueId/edit',
  adminVenueEdit: (venueId: string) => `/admin/venues/${venueId}/edit`,
  notFound: '/not-found',
} as const
